version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ls
      - restore_cache:
          keys:
            - sbt-{{ checksum "build.sbt" }}
            - sbt-
      - run:
          name: Compile
          command: sbt compile
      - save_cache:
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
          key: sbt-{{ checksum "build.sbt" }}
      - run:
          name: Unit Test
          command: sbt test
#      - persist_to_workspace:
#          root: /home/circleci
#          paths:
#            - .
#
#  deploy:
#    docker:
#      - image: circleci/openjdk:8-jdk
#    environment:
#      JVM_OPTS: -Xmx3200m
#      TERM: dumb
#    steps:
#      - attach_workspace:
#          at: /home/circleci
      - setup_remote_docker
      - run:
          name: Install pip
          command: |
            sudo apt update
            sudo apt upgrade
            sudo apt install python2.7 python-pip
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Docker Login
          command: $(aws ecr get-login --no-include-email)
      - run:
          name: Build & Push Image
          command: sbt publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
#      - deploy:
#          filters:
#            branches:
#              only: master
#          requires:
#            - build
